services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-elasticsearch
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
    driver: local


#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.4.0
#    restart: always
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

#  spring-app:
#    image: elastic-search-spring-application
#    container_name: spring-app
#    depends_on:
#      - elasticsearch
#    environment:
#      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
#    ports:
#      - "8080:8080"