services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-elasticsearch
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: on-failure # Restart container if it fails
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s  # Retry after 5 seconds
          max_attempts: 5  # Number max of retries
          window: 30s  # Temporal window to retry

volumes:
  elastic_data:
    driver: local